replicaCount: 2

image:
  repository: gswack/portfolio-app
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: ENV
    value: production
  - name: DEBUG
    value: "false"
    
service:
  type: NodePort
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false  # or true, depending on your needs
