name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Debug Docker username
      run: echo "Using Docker username ${{ secrets.DOCKER_USERNAME }}"


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: gswack
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Verify Docker login
      run: docker info

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gswack/portfolio-app:latest

    - name: Lint Helm chart
      run: helm lint ./charts/myapp

    # Optional: Trigger ArgoCD sync via Webhook
    # - name: Trigger ArgoCD sync
      # if: success()
      # run: |
        # curl -X POST ${{ secrets.ARGOCD_WEBHOOK_URL }}
